[build]
  functions = "functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Request-Method = "GET, POST, PUT, DELETE"
    Content-Type = "application/json"
